// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClccMoytSEMej8kpTD4M5BnNwe7RWdrPw',
    appId: '1:158045791719:web:5025cc856ac536da3cc942',
    messagingSenderId: '158045791719',
    projectId: 'nolar-plus',
    authDomain: 'nolar-plus.firebaseapp.com',
    storageBucket: 'nolar-plus.appspot.com',
    measurementId: 'G-W5RHYZEC7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ1N9oSa3q5VZPCGlnIXp_HMcQC4z_CQs',
    appId: '1:158045791719:android:a965dfbd72c7b4183cc942',
    messagingSenderId: '158045791719',
    projectId: 'nolar-plus',
    storageBucket: 'nolar-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRW8EYUXAzzCkPthLr5ZrGMQDXzX40m8M',
    appId: '1:158045791719:ios:8e42a26c1123a2963cc942',
    messagingSenderId: '158045791719',
    projectId: 'nolar-plus',
    storageBucket: 'nolar-plus.appspot.com',
    androidClientId: '158045791719-dioe82kck1tfrgi5pkdkl94b8m0gdhsj.apps.googleusercontent.com',
    iosClientId: '158045791719-4dmuarbsf35005vn98bkil6hcue3g81h.apps.googleusercontent.com',
    iosBundleId: 'com.example.nolar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRW8EYUXAzzCkPthLr5ZrGMQDXzX40m8M',
    appId: '1:158045791719:ios:8e42a26c1123a2963cc942',
    messagingSenderId: '158045791719',
    projectId: 'nolar-plus',
    storageBucket: 'nolar-plus.appspot.com',
    androidClientId: '158045791719-dioe82kck1tfrgi5pkdkl94b8m0gdhsj.apps.googleusercontent.com',
    iosClientId: '158045791719-4dmuarbsf35005vn98bkil6hcue3g81h.apps.googleusercontent.com',
    iosBundleId: 'com.example.nolar',
  );
}
